### PR TITLE
MOO-578: Fix text redundancy on visit details

### PR DESCRIPTION
**Pull request by edrisse**

### CODE REVIEW

**Comment by lauravignoli** [comment]
@edrisse Please use the subtask name in the commits for easy identification.

**Comment by lauravignoli** [comment]
@edrisse Wouldn't a group id be a better way to fix the display?

**Comment by Guimino** [comment]
> @edrisse Wouldn't a group id be a better way to fix the display?

I agree with you @lauravignoli , probably there is a grouping issue

**Comment by lauravignoli** [comment]
@Guimino @edrisse Have been thinking of a way of doing this using different grouping but I don't think it's possible. Have you found a way?

**Pull request merged**
